apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: "public.ecr.aws/k7l1b1b0/ecr-br-test:0.9.10"
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
